{
  "2021": [
    {
        "name": "Reviewer",
        "venue": "Transactions on Software Engineering (TSE)"
      },
    {
        "name": "Reviewer",
        "venue": "Journal of Computer Science and Technology (JCST)"
      },
    {
        "name": "Reviewer",
        "venue": "Journal of Software"
      },
      {
        "name": "Data Showcase Committee Member",
        "venue": "The 19th Working Conference on Mining Software Repositories (MSR 2022 Data and Tool Showcase Track)"
      }

  ]
}
  
